/*
 * Copyright (c) 2021, Krisna Pranav
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include <libweb/bindings/CSSStyleSheetConstructor.h>
#include <libweb/bindings/CSSStyleSheetPrototype.h>
#include <libweb/bindings/CanvasRenderingContext2DConstructor.h>
#include <libweb/bindings/CanvasRenderingContext2DPrototype.h>
#include <libweb/bindings/CharacterDataConstructor.h>
#include <libweb/bindings/CharacterDataPrototype.h>
#include <libweb/bindings/CloseEventConstructor.h>
#include <libweb/bindings/CloseEventPrototype.h>
#include <libweb/bindings/CommentConstructor.h>
#include <libweb/bindings/CommentPrototype.h>
#include <libweb/bindings/DOMExceptionConstructor.h>
#include <libweb/bindings/DOMExceptionPrototype.h>
#include <libweb/bindings/DOMImplementationConstructor.h>
#include <libweb/bindings/DOMImplementationPrototype.h>
#include <libweb/bindings/DOMParserConstructor.h>
#include <libweb/bindings/DOMParserPrototype.h>
#include <libweb/bindings/DocumentConstructor.h>
#include <libweb/bindings/DocumentFragmentConstructor.h>
#include <libweb/bindings/DocumentFragmentPrototype.h>
#include <libweb/bindings/DocumentPrototype.h>
#include <libweb/bindings/DocumentTypeConstructor.h>
#include <libweb/bindings/DocumentTypePrototype.h>
#include <libweb/bindings/ElementConstructor.h>
#include <libweb/bindings/ElementPrototype.h>
#include <libweb/bindings/EventConstructor.h>
#include <libweb/bindings/EventPrototype.h>
#include <libweb/bindings/EventTargetConstructor.h>
#include <libweb/bindings/EventTargetPrototype.h>
#include <libweb/bindings/HTMLAnchorElementConstructor.h>
#include <libweb/bindings/HTMLAnchorElementPrototype.h>
#include <libweb/bindings/HTMLAreaElementConstructor.h>
#include <libweb/bindings/HTMLAreaElementPrototype.h>
#include <libweb/bindings/HTMLAudioElementConstructor.h>
#include <libweb/bindings/HTMLAudioElementPrototype.h>
#include <libweb/bindings/HTMLBRElementConstructor.h>
#include <libweb/bindings/HTMLBRElementPrototype.h>
#include <libweb/bindings/HTMLBaseElementConstructor.h>
#include <libweb/bindings/HTMLBaseElementPrototype.h>
#include <libweb/bindings/HTMLBodyElementConstructor.h>
#include <libweb/bindings/HTMLBodyElementPrototype.h>
#include <libweb/bindings/HTMLButtonElementConstructor.h>
#include <libweb/bindings/HTMLButtonElementPrototype.h>
#include <libweb/bindings/HTMLCanvasElementConstructor.h>
#include <libweb/bindings/HTMLCanvasElementPrototype.h>
#include <libweb/bindings/HTMLDListElementConstructor.h>
#include <libweb/bindings/HTMLDListElementPrototype.h>
#include <libweb/bindings/HTMLDataElementConstructor.h>
#include <libweb/bindings/HTMLDataElementPrototype.h>
#include <libweb/bindings/HTMLDataListElementConstructor.h>
#include <libweb/bindings/HTMLDataListElementPrototype.h>
#include <libweb/bindings/HTMLDetailsElementConstructor.h>
#include <libweb/bindings/HTMLDetailsElementPrototype.h>
#include <libweb/bindings/HTMLDialogElementConstructor.h>
#include <libweb/bindings/HTMLDialogElementPrototype.h>
#include <libweb/bindings/HTMLDirectoryElementConstructor.h>
#include <libweb/bindings/HTMLDirectoryElementPrototype.h>
#include <libweb/bindings/HTMLDivElementConstructor.h>
#include <libweb/bindings/HTMLDivElementPrototype.h>
#include <libweb/bindings/HTMLElementConstructor.h>
#include <libweb/bindings/HTMLElementPrototype.h>
#include <libweb/bindings/HTMLEmbedElementConstructor.h>
#include <libweb/bindings/HTMLEmbedElementPrototype.h>
#include <libweb/bindings/HTMLFieldSetElementConstructor.h>
#include <libweb/bindings/HTMLFieldSetElementPrototype.h>
#include <libweb/bindings/HTMLFontElementConstructor.h>
#include <libweb/bindings/HTMLFontElementPrototype.h>
#include <libweb/bindings/HTMLFormElementConstructor.h>
#include <libweb/bindings/HTMLFormElementPrototype.h>
#include <libweb/bindings/HTMLFrameElementConstructor.h>
#include <libweb/bindings/HTMLFrameElementPrototype.h>
#include <libweb/bindings/HTMLFrameSetElementConstructor.h>
#include <libweb/bindings/HTMLFrameSetElementPrototype.h>
#include <libweb/bindings/HTMLHRElementConstructor.h>
#include <libweb/bindings/HTMLHRElementPrototype.h>
#include <libweb/bindings/HTMLHeadElementConstructor.h>
#include <libweb/bindings/HTMLHeadElementPrototype.h>
#include <libweb/bindings/HTMLHeadingElementConstructor.h>
#include <libweb/bindings/HTMLHeadingElementPrototype.h>
#include <libweb/bindings/HTMLHtmlElementConstructor.h>
#include <libweb/bindings/HTMLHtmlElementPrototype.h>
#include <libweb/bindings/HTMLIFrameElementConstructor.h>
#include <libweb/bindings/HTMLIFrameElementPrototype.h>
#include <libweb/bindings/HTMLImageElementConstructor.h>
#include <libweb/bindings/HTMLImageElementPrototype.h>
#include <libweb/bindings/HTMLInputElementConstructor.h>
#include <libweb/bindings/HTMLInputElementPrototype.h>
#include <libweb/bindings/HTMLLIElementConstructor.h>
#include <libweb/bindings/HTMLLIElementPrototype.h>
#include <libweb/bindings/HTMLLabelElementConstructor.h>
#include <libweb/bindings/HTMLLabelElementPrototype.h>
#include <libweb/bindings/HTMLLegendElementConstructor.h>
#include <libweb/bindings/HTMLLegendElementPrototype.h>
#include <libweb/bindings/HTMLLinkElementConstructor.h>
#include <libweb/bindings/HTMLLinkElementPrototype.h>
#include <libweb/bindings/HTMLMapElementConstructor.h>
#include <libweb/bindings/HTMLMapElementPrototype.h>
#include <libweb/bindings/HTMLMarqueeElementConstructor.h>
#include <libweb/bindings/HTMLMarqueeElementPrototype.h>
#include <libweb/bindings/HTMLMediaElementConstructor.h>
#include <libweb/bindings/HTMLMediaElementPrototype.h>
#include <libweb/bindings/HTMLMenuElementConstructor.h>
#include <libweb/bindings/HTMLMenuElementPrototype.h>
#include <libweb/bindings/HTMLMetaElementConstructor.h>
#include <libweb/bindings/HTMLMetaElementPrototype.h>
#include <libweb/bindings/HTMLMeterElementConstructor.h>
#include <libweb/bindings/HTMLMeterElementPrototype.h>
#include <libweb/bindings/HTMLModElementConstructor.h>
#include <libweb/bindings/HTMLModElementPrototype.h>
#include <libweb/bindings/HTMLOListElementConstructor.h>
#include <libweb/bindings/HTMLOListElementPrototype.h>
#include <libweb/bindings/HTMLObjectElementConstructor.h>
#include <libweb/bindings/HTMLObjectElementPrototype.h>
#include <libweb/bindings/HTMLOptGroupElementConstructor.h>
#include <libweb/bindings/HTMLOptGroupElementPrototype.h>
#include <libweb/bindings/HTMLOptionElementConstructor.h>
#include <libweb/bindings/HTMLOptionElementPrototype.h>
#include <libweb/bindings/HTMLOutputElementConstructor.h>
#include <libweb/bindings/HTMLOutputElementPrototype.h>
#include <libweb/bindings/HTMLParagraphElementConstructor.h>
#include <libweb/bindings/HTMLParagraphElementPrototype.h>
#include <libweb/bindings/HTMLParamElementConstructor.h>
#include <libweb/bindings/HTMLParamElementPrototype.h>
#include <libweb/bindings/HTMLPictureElementConstructor.h>
#include <libweb/bindings/HTMLPictureElementPrototype.h>
#include <libweb/bindings/HTMLPreElementConstructor.h>
#include <libweb/bindings/HTMLPreElementPrototype.h>
#include <libweb/bindings/HTMLProgressElementConstructor.h>
#include <libweb/bindings/HTMLProgressElementPrototype.h>
#include <libweb/bindings/HTMLQuoteElementConstructor.h>
#include <libweb/bindings/HTMLQuoteElementPrototype.h>
#include <libweb/bindings/HTMLScriptElementConstructor.h>
#include <libweb/bindings/HTMLScriptElementPrototype.h>
#include <libweb/bindings/HTMLSelectElementConstructor.h>
#include <libweb/bindings/HTMLSelectElementPrototype.h>
#include <libweb/bindings/HTMLSlotElementConstructor.h>
#include <libweb/bindings/HTMLSlotElementPrototype.h>
#include <libweb/bindings/HTMLSourceElementConstructor.h>
#include <libweb/bindings/HTMLSourceElementPrototype.h>
#include <libweb/bindings/HTMLSpanElementConstructor.h>
#include <libweb/bindings/HTMLSpanElementPrototype.h>
#include <libweb/bindings/HTMLStyleElementConstructor.h>
#include <libweb/bindings/HTMLStyleElementPrototype.h>
#include <libweb/bindings/HTMLTableCaptionElementConstructor.h>
#include <libweb/bindings/HTMLTableCaptionElementPrototype.h>
#include <libweb/bindings/HTMLTableCellElementConstructor.h>
#include <libweb/bindings/HTMLTableCellElementPrototype.h>
#include <libweb/bindings/HTMLTableColElementConstructor.h>
#include <libweb/bindings/HTMLTableColElementPrototype.h>
#include <libweb/bindings/HTMLTableElementConstructor.h>
#include <libweb/bindings/HTMLTableElementPrototype.h>
#include <libweb/bindings/HTMLTableRowElementConstructor.h>
#include <libweb/bindings/HTMLTableRowElementPrototype.h>
#include <libweb/bindings/HTMLTableSectionElementConstructor.h>
#include <libweb/bindings/HTMLTableSectionElementPrototype.h>
#include <libweb/bindings/HTMLTemplateElementConstructor.h>
#include <libweb/bindings/HTMLTemplateElementPrototype.h>
#include <libweb/bindings/HTMLTextAreaElementConstructor.h>
#include <libweb/bindings/HTMLTextAreaElementPrototype.h>
#include <libweb/bindings/HTMLTimeElementConstructor.h>
#include <libweb/bindings/HTMLTimeElementPrototype.h>
#include <libweb/bindings/HTMLTitleElementConstructor.h>
#include <libweb/bindings/HTMLTitleElementPrototype.h>
#include <libweb/bindings/HTMLTrackElementConstructor.h>
#include <libweb/bindings/HTMLTrackElementPrototype.h>
#include <libweb/bindings/HTMLUListElementConstructor.h>
#include <libweb/bindings/HTMLUListElementPrototype.h>
#include <libweb/bindings/HTMLUnknownElementConstructor.h>
#include <libweb/bindings/HTMLUnknownElementPrototype.h>
#include <libweb/bindings/HTMLVideoElementConstructor.h>
#include <libweb/bindings/HTMLVideoElementPrototype.h>
#include <libweb/bindings/ImageConstructor.h>
#include <libweb/bindings/ImageDataConstructor.h>
#include <libweb/bindings/ImageDataPrototype.h>
#include <libweb/bindings/MessageEventConstructor.h>
#include <libweb/bindings/MessageEventPrototype.h>
#include <libweb/bindings/MouseEventConstructor.h>
#include <libweb/bindings/MouseEventPrototype.h>
#include <libweb/bindings/NodeConstructor.h>
#include <libweb/bindings/NodePrototype.h>
#include <libweb/bindings/PerformanceConstructor.h>
#include <libweb/bindings/PerformancePrototype.h>
#include <libweb/bindings/PerformanceTimingConstructor.h>
#include <libweb/bindings/PerformanceTimingPrototype.h>
#include <libweb/bindings/ProcessingInstructionConstructor.h>
#include <libweb/bindings/ProcessingInstructionPrototype.h>
#include <libweb/bindings/ProgressEventConstructor.h>
#include <libweb/bindings/ProgressEventPrototype.h>
#include <libweb/bindings/SVGElementConstructor.h>
#include <libweb/bindings/SVGElementPrototype.h>
#include <libweb/bindings/SVGGeometryElementConstructor.h>
#include <libweb/bindings/SVGGeometryElementPrototype.h>
#include <libweb/bindings/SVGGraphicsElementConstructor.h>
#include <libweb/bindings/SVGGraphicsElementPrototype.h>
#include <libweb/bindings/SVGPathElementConstructor.h>
#include <libweb/bindings/SVGPathElementPrototype.h>
#include <libweb/bindings/SVGSVGElementConstructor.h>
#include <libweb/bindings/SVGSVGElementPrototype.h>
#include <libweb/bindings/ScreenConstructor.h>
#include <libweb/bindings/ScreenPrototype.h>
#include <libweb/bindings/ShadowRootConstructor.h>
#include <libweb/bindings/ShadowRootPrototype.h>
#include <libweb/bindings/StyleSheetConstructor.h>
#include <libweb/bindings/StyleSheetListConstructor.h>
#include <libweb/bindings/StyleSheetListPrototype.h>
#include <libweb/bindings/StyleSheetPrototype.h>
#include <libweb/bindings/SubmitEventConstructor.h>
#include <libweb/bindings/SubmitEventPrototype.h>
#include <libweb/bindings/TextConstructor.h>
#include <libweb/bindings/TextPrototype.h>
#include <libweb/bindings/UIEventConstructor.h>
#include <libweb/bindings/UIEventPrototype.h>
#include <libweb/bindings/WebSocketConstructor.h>
#include <libweb/bindings/WebSocketPrototype.h>
#include <libweb/bindings/XMLHttpRequestConstructor.h>
#include <libweb/bindings/XMLHttpRequestEventTargetConstructor.h>
#include <libweb/bindings/XMLHttpRequestEventTargetPrototype.h>
#include <libweb/bindings/XMLHttpRequestPrototype.h>

#define ADD_WINDOW_OBJECT_CONSTRUCTOR_AND_PROTOTYPE(interface_name, constructor_name, prototype_name)                                \
    {                                                                                                                                \
        auto& constructor = ensure_web_constructor<constructor_name>(#interface_name);                                               \
        constructor.define_direct_property(vm.names.name, js_string(vm, #interface_name), JS::Attribute::Configurable);              \
        auto& prototype = ensure_web_prototype<prototype_name>(#interface_name);                                                     \
        prototype.define_direct_property(vm.names.constructor, &constructor, JS::Attribute::Writable | JS::Attribute::Configurable); \
    }

#define ADD_WINDOW_OBJECT_INTERFACE(interface_name) \
    ADD_WINDOW_OBJECT_CONSTRUCTOR_AND_PROTOTYPE(interface_name, interface_name##Constructor, interface_name##Prototype)

#define ADD_WINDOW_OBJECT_INTERFACES                       \
    auto& vm = this->vm();                                 \
    ADD_WINDOW_OBJECT_INTERFACE(CanvasRenderingContext2D)  \
    ADD_WINDOW_OBJECT_INTERFACE(CharacterData)             \
    ADD_WINDOW_OBJECT_INTERFACE(CloseEvent)                \
    ADD_WINDOW_OBJECT_INTERFACE(Comment)                   \
    ADD_WINDOW_OBJECT_INTERFACE(CSSStyleSheet)             \
    ADD_WINDOW_OBJECT_INTERFACE(DocumentFragment)          \
    ADD_WINDOW_OBJECT_INTERFACE(Document)                  \
    ADD_WINDOW_OBJECT_INTERFACE(DocumentType)              \
    ADD_WINDOW_OBJECT_INTERFACE(DOMException)              \
    ADD_WINDOW_OBJECT_INTERFACE(DOMImplementation)         \
    ADD_WINDOW_OBJECT_INTERFACE(DOMParser)                 \
    ADD_WINDOW_OBJECT_INTERFACE(Element)                   \
    ADD_WINDOW_OBJECT_INTERFACE(Event)                     \
    ADD_WINDOW_OBJECT_INTERFACE(EventTarget)               \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLAnchorElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLAreaElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLAudioElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLBaseElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLBodyElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLBRElement)             \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLButtonElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLCanvasElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDataElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDataListElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDetailsElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDialogElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDirectoryElement)      \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDivElement)            \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLDListElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLElement)               \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLEmbedElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLFieldSetElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLFontElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLFormElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLFrameElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLFrameSetElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLHeadElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLHeadingElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLHRElement)             \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLHtmlElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLIFrameElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLImageElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLInputElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLLabelElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLLegendElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLLIElement)             \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLLinkElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMapElement)            \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMarqueeElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMediaElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMenuElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMetaElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLMeterElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLModElement)            \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLObjectElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLOListElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLOptGroupElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLOptionElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLOutputElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLParagraphElement)      \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLParamElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLPictureElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLPreElement)            \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLProgressElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLQuoteElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLScriptElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLSelectElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLSlotElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLSourceElement)         \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLSpanElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLStyleElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableCaptionElement)   \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableCellElement)      \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableColElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableRowElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTableSectionElement)   \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTemplateElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTextAreaElement)       \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTimeElement)           \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTitleElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLTrackElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLUListElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLUnknownElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(HTMLVideoElement)          \
    ADD_WINDOW_OBJECT_INTERFACE(ImageData)                 \
    ADD_WINDOW_OBJECT_INTERFACE(MessageEvent)              \
    ADD_WINDOW_OBJECT_INTERFACE(MouseEvent)                \
    ADD_WINDOW_OBJECT_INTERFACE(Node)                      \
    ADD_WINDOW_OBJECT_INTERFACE(Performance)               \
    ADD_WINDOW_OBJECT_INTERFACE(PerformanceTiming)         \
    ADD_WINDOW_OBJECT_INTERFACE(ProcessingInstruction)     \
    ADD_WINDOW_OBJECT_INTERFACE(ProgressEvent)             \
    ADD_WINDOW_OBJECT_INTERFACE(Screen)                    \
    ADD_WINDOW_OBJECT_INTERFACE(ShadowRoot)                \
    ADD_WINDOW_OBJECT_INTERFACE(StyleSheet)                \
    ADD_WINDOW_OBJECT_INTERFACE(StyleSheetList)            \
    ADD_WINDOW_OBJECT_INTERFACE(SubmitEvent)               \
    ADD_WINDOW_OBJECT_INTERFACE(SVGElement)                \
    ADD_WINDOW_OBJECT_INTERFACE(SVGGeometryElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(SVGGraphicsElement)        \
    ADD_WINDOW_OBJECT_INTERFACE(SVGPathElement)            \
    ADD_WINDOW_OBJECT_INTERFACE(SVGSVGElement)             \
    ADD_WINDOW_OBJECT_INTERFACE(Text)                      \
    ADD_WINDOW_OBJECT_INTERFACE(UIEvent)                   \
    ADD_WINDOW_OBJECT_INTERFACE(WebSocket)                 \
    ADD_WINDOW_OBJECT_INTERFACE(XMLHttpRequest)            \
    ADD_WINDOW_OBJECT_INTERFACE(XMLHttpRequestEventTarget) \
    ADD_WINDOW_OBJECT_CONSTRUCTOR_AND_PROTOTYPE(Image, ImageConstructor, HTMLImageElementPrototype)
