#include <arpa/inet.h>
#include <ak/ether.h>
#include <math.h>
#include <sockios.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <unistd.h>
#include "host.h"