/**
 * @file config.h
 * @author Krisna Pranav
 * @version 6.0
 * @date 2025-03-27
 *
 * @copyright Copyright (c) 2021-2025 pranaOS Developers, Krisna Pranav
 *
 */

#define INITIAL_PAGES_SIZE (1 * MB)

#define STAGE2_WORKING_HEAP_SIZE (4 * MB)
#define STAGE2_STACK_SIZE (32 * KB) 

#define EXCEPT_STACK_SIZE (32 * KB)
#define INT_STACK_SIZE (32 * KB)

#define KERNEL_CONTEXT_SIZE (32 * KB)
#define SYSCALL_CONTEXT_SIZE (32 * KB)
#define PROCESS_CONTEXT_SIZE (32 * KB)

#define PAGE_INVAL_QUEUE_LENGTH 4096

#define TABLE_MAX_BUCKETS 131072

#define RUNLOOP_TIMER_MAX_PERIOD_US 100000
#define RUNLOOP_TIMER_MIN_PERIOD_US 1000

#define MAX_THREADS 8192

#define FREE_KERNEL_CONTEXT_QUEUE_SIZE 8
#define FREE_SYSCALL_CONTEXT_QUEUE_SIZE 8
#define FREE_PROCESS_CONTEXT_QUEUE_SIZE 8

#define CPU_QUEUE_SIZE 512

#define BHQUEUE_SIZE 8192
#define RUNQUEUE_SIZE 8192
#define ASYNC_QUEUE_1_SIZE 65536

#define MUTEX_ACQUIRE_SPIN_LIMIT (1ull << 20)

#define DEFAULT_CACHELINE_SIZE 64

#define TFS_LOG_INITIAL_SIZE SECTOR_SIZE
#define TFS_LOG_DEFAULT_EXTENSION_SIZE (512 * KB)
#define TFS_LOG_FLUSH_DELAY_SECONDS 1

#define TFS_LOG_COMPACT_OBSOLETE 8192

#define TFS_LOG_COMPACT_RATIO 2

#define XENNET_INIT_RX_BUFFERS_FACTOR 4
#define XENNET_RX_SERVICEQUEUE_DEPTH 512
#define XENNET_TX_SERVICEQUEUE_DEPTH 512

#define MEM_CLEAN_THRESHOLD (64 * MB)
#define MEM_CLEAN_THRESHOLD_SHIFT 6
#define PAGECACHE_SCAN_PERIOD_SECONDS 5
#define PAGEHEAP_MEMORY_RESERVE (8 * MB)
#define PAGEHEAP_LOWMEM_MEMORY_RESERVE (4 * MB)
#define PAGEHEAP_LOWMEM_PAGESIZE (1 * MB)
#define LOW_MEMORY_THRESHOLD (64 * MB)
#define SG_FRAG_BYTE_THRESHOLD (128 * KB)
#define PAGECACHE_MAX_SG_ENTRIES 8192

#define BALLOON_MEMORY_MINIMUM (16 * MB)

#define NET_RX_BUFFERS_RETAIN 64
#define STORAGE_REQUESTS_RETAIN 64
#define PAGECACHE_PAGES_RETAIN 64
#define PAGECACHE_COMPLETIONS_RETAIN 64

#define MAX_MCACHE_ORDER 16
#define MAX_LOWMEM_MCACHE_ORDER 11

#define DEFAULT_TRACE_ARRAY_SIZE (512ULL << 20)

#define KLOG_DUMP_SIZE (4 * KB)

#define FRAME_TRACE_DEPTH 32
#define STACK_TRACE_DEPTH 32

#define UNIX_SHUTDOWN_TIMEOUT_SECS 30

#define LWIP_LOCK_SPIN_ITERATIONS (1ull << 16)