if (PLATFORM STREQUAL x86_64)
    set(pranaOSPlatform x86_64)
    set(pranaOSPlatformMacro PLATFORM_x86_64)
elseif (PLATFORM STREQUAL raspi4)
    set(pranaOSPlatform raspi4)
    set(pranaOSPlatformMacro PLATFORM_RASPI4)
elseif (PLATFORM STREQUAL raspi2)
    set(pranaOSPlatform raspi2)
    set(pranaOSPlatformMacro PLATFORM_RASPI2)
elseif (PLATFORM STREQUAL bochs)
    set(pranaOSPlatform bochs)
    set(pranaOSPlatformMacro PLATFORM_BOCHS)
elseif (PLATFORM STREQUAL qemu)
    set(pranaOSPlatform qemu)
    set(pranaOSPlatformMacro PLATFORM_QEMU)
else ()
    message(WARNING "Unexpected PLATFORM ${PLATFORM}, using default value \"bochs\"")
    set(PLATFORM bochs)
    set(pranaOSPlatform bochs)
    set(pranaOSPlatformMacro PLATFORM_BOCHS)
endif ()

message(STATUS "pranaOSPlatform is ${pranaOSPlatform}")