name: PSharp Rust CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./psharp
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./psharp
      run: cargo test --verbose

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./psharp
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./psharp
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./psharp
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./psharp
      run: cargo test --verbose
